name: Release

on:
  push:
    tags:
      - "v*.*.*"

# additional permissions for provided GitHub token to create new release
permissions:
  contents: write

jobs:
  build-release-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build a simple jar with all dependencies
        run: ./gradlew shadowJar

      - name: Save JRE bundle artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ 'GradleOfflineTools-windows.jar' }}
          path: ${{ 'app/build/libs/app-[\\.1-9]*.jar' }}
          if-no-files-found: error
          retention-days: 1

  build-release-mac:
    runs-on: mac-latest 
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build a simple jar with all dependencies
        run: ./gradlew shadowJar

      - name: Save JRE bundle artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ 'GradleOfflineTools-mac.jar' }}
          path: ${{ 'app/build/libs/app-[\\.1-9]*.jar' }}
          if-no-files-found: error
          retention-days: 1
          
  build-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build a simple jar with all dependencies
        run: ./gradlew shadowJar

      - name: Save JRE bundle artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ 'GradleOfflineTools-linux.jar' }}
          path: ${{ 'app/build/libs/app-[\\.1-9]*.jar' }}
          if-no-files-found: error
          retention-days: 1
    
  release:
    needs: [build-release-win, build-release-mac, build-release-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
      
      - run: ls -l
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: GradleOfflineTools
          draft: true
          fail_on_unmatched_files: true
          files: GradleOfflineTools*.jar
